@startuml

interface AuthenticationManager

class ProviderManager

class DaoAuthenticationProvider
class XxxAuthenticationProvider

class XxxUserDetailsService

AuthenticationManager <|.. ProviderManager

ProviderManager o-- DaoAuthenticationProvider
ProviderManager o-- XxxAuthenticationProvider


DaoAuthenticationProvider ..|> AuthenticationProvider
XxxAuthenticationProvider ..|> AuthenticationProvider

XxxUserDetailsService -o DaoAuthenticationProvider
XxxUserDetailsService ..|> UserDetailsService


@enduml